server:
  host: "0.0.0.0"
  port: 8081  # 使用不同的端口

database:
  analyzer_db:
    host: "localhost"
    port: 3306
    user: "master_user"
    password: "master_password_123"
    dbname: "blockchain_master"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"

analyzer:
  interval: 10  # 分析间隔（秒）
  batch_size: 100  # 批量处理大小 