server:
  host: "localhost"
  port: 8080

database:
  # 采集节点数据库配置
  collector_db:
    host: "localhost"
    port: 3306
    user: "collector_user"
    password: "collector_password_123"
    dbname: "collector_db"
  
  # 主节点数据库配置
  master_db:
    host: "localhost"
    port: 3306
    user: "master_user"
    password: "master_password_123"
    dbname: "blockchain_master"
  
  # 只读数据库配置
  readonly_db:
    host: "localhost"
    port: 3306
    user: "reader_user"
    password: "reader_password_123"
    dbname: "collector_db"  # 或 blockchain_master
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

notification:
  telegram:
    token: ""
    chatID: ""
  discord:
    token: ""
    channelID: "" 